// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDofguswD8mbk8pf1EWRvtM6jKGIxyK9Rk',
    appId: '1:312471573376:web:2fec59edc451dacc8d2765',
    messagingSenderId: '312471573376',
    projectId: 'socialmedia-179cf',
    authDomain: 'socialmedia-179cf.firebaseapp.com',
    storageBucket: 'socialmedia-179cf.appspot.com',
    measurementId: 'G-MBCX9LRK12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8HmSLN8VvxgC8SbZ1xvRl_GT0yvDkEEU',
    appId: '1:312471573376:android:cb384684a7766bde8d2765',
    messagingSenderId: '312471573376',
    projectId: 'socialmedia-179cf',
    storageBucket: 'socialmedia-179cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA01fIKn8x8mkkj2R_MCp_7ISdDCjz7Le0',
    appId: '1:312471573376:ios:57b86f759660e90e8d2765',
    messagingSenderId: '312471573376',
    projectId: 'socialmedia-179cf',
    storageBucket: 'socialmedia-179cf.appspot.com',
    iosClientId: '312471573376-eqra58gpal20pudfv77kmsr14sd5gra6.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA01fIKn8x8mkkj2R_MCp_7ISdDCjz7Le0',
    appId: '1:312471573376:ios:57b86f759660e90e8d2765',
    messagingSenderId: '312471573376',
    projectId: 'socialmedia-179cf',
    storageBucket: 'socialmedia-179cf.appspot.com',
    iosClientId: '312471573376-eqra58gpal20pudfv77kmsr14sd5gra6.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
